runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: yarn set version 3.5.0
      shell: bash

    - run: yarn install --frozen-lockfile
      shell: bash
